name: Build distributions

on:
  pull_request:
  release:
    types:
      - published

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          name: inmoose_sdist
          path: dist/inmoose-*.tar.gz

  build_wheels:
    needs: [build_sdist]
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: inmoose_sdist
          path: sdist

      - run: mv sdist/*.tar.gz sdist/inmoose.tar.gz

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.3
        env:
          CIBW_BUILD_FRONTEND: "build"
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-*"
          CIBW_SKIP: "*-musllinux* *i686"
          CIBW_TEST_COMMAND: "python -m unittest discover -s {package}/tests"
        with:
          package-dir: sdist/inmoose.tar.gz

